var __createBinding=this&&this.__createBinding||(Object.create?function(b,g,e,l){void 0===l&&(l=e);var m=Object.getOwnPropertyDescriptor(g,e);if(!m||("get"in m?!g.__esModule:m.writable||m.configurable))m={enumerable:!0,get:function(){return g[e]}};Object.defineProperty(b,l,m)}:function(b,g,e,l){void 0===l&&(l=e);b[l]=g[e]}),__setModuleDefault=this&&this.__setModuleDefault||(Object.create?function(b,g){Object.defineProperty(b,"default",{enumerable:!0,value:g})}:function(b,g){b["default"]=g}),__importStar=
this&&this.__importStar||function(b){if(b&&b.__esModule)return b;var g={};if(null!=b)for(var e in b)"default"!==e&&Object.prototype.hasOwnProperty.call(b,e)&&__createBinding(g,b,e);__setModuleDefault(g,b);return g};Object.defineProperty(exports,"__esModule",{value:!0});exports.decodeBinaryNode=exports.decodeDecompressedBinaryNode=exports.decompressingIfRequired=void 0;
const zlib_1=require("zlib"),constants=__importStar(require("./constants")),jid_utils_1=require("./jid-utils"),decompressingIfRequired=b=>b=2&b.readUInt8()?(0,zlib_1.inflateSync)(b.slice(1)):b.slice(1);exports.decompressingIfRequired=decompressingIfRequired;
const decodeDecompressedBinaryNode=(b,g,e={index:0})=>{const {DOUBLE_BYTE_TOKENS:l,SINGLE_BYTE_TOKENS:m,TAGS:d}=g,u=a=>{if(e.index+a>b.length)throw Error("end of stream");},t=()=>{const a=b[e.index];e.index+=1;return a},h=()=>{u(1);return t()},q=a=>{u(a);const c=b.slice(e.index,e.index+a);e.index+=a;return c},w=(a,c=!1)=>{u(a);let f=0;for(let n=0;n<a;n++){const v=c?n:a-1-n;f|=t()<<8*v}return f},z=()=>{u(3);return((t()&15)<<16)+(t()<<8)+t()},D=a=>{if(0<=a&&9>=a)return 48+a;switch(a){case 10:return 45;
case 11:return 46;case 15:return 0;default:throw Error("invalid nibble: "+a);}},A=(a,c)=>{if(a===d.NIBBLE_8)return D(c);if(a===d.HEX_8){if(!(0<=c&&16>c))throw Error("invalid hex: "+c);return 10>c?48+c:65+c-10}throw Error("unknown tag: "+a);},B=a=>{switch(a){case d.LIST_EMPTY:return 0;case d.LIST_8:return h();case d.LIST_16:return w(2);default:throw Error("invalid tag for list size: "+a);}},p=a=>{if(1<=a&&a<m.length)return m[a]||"";switch(a){case d.DICTIONARY_0:case d.DICTIONARY_1:case d.DICTIONARY_2:case d.DICTIONARY_3:var c=
a-d.DICTIONARY_0;a=h();var f=l[c];if(!f)throw Error(`Invalid double token dict (${c})`);c=f[a];if("undefined"===typeof c)throw Error(`Invalid double token (${a})`);return c;case d.LIST_EMPTY:return"";case d.BINARY_8:return q(h()).toString("utf-8");case d.BINARY_20:return q(z()).toString("utf-8");case d.BINARY_32:return q(w(4)).toString("utf-8");case d.JID_PAIR:a=p(h());if(c=p(h()))a=(a||"")+"@"+c;else throw Error("invalid jid pair: "+a+", "+c);return a;case d.AD_JID:return a=h(),c=h(),f=p(h()),(0,jid_utils_1.jidEncode)(f,
0===a?"s.whatsapp.net":"lid",c);case d.HEX_8:case d.NIBBLE_8:c=h();f="";for(let n=0;n<(c&127);n++){const v=h();f+=String.fromCharCode(A(a,(v&240)>>4));f+=String.fromCharCode(A(a,v&15))}0!==c>>7&&(f=f.slice(0,-1));return f;default:throw Error("invalid string with tag: "+a);}};var r=a=>{const c=[];a=B(a);for(let f=0;f<a;f++)c.push((0,exports.decodeDecompressedBinaryNode)(b,g,e));return c},k=B(h());const x=p(h());if(!k||!x.length)throw Error("invalid node");const C={};let y;if(0===k||!x)throw Error("invalid node");
const E=k-1>>1;for(let a=0;a<E;a++){const c=p(h()),f=p(h());C[c]=f}if(0===k%2)if(k=h(),k===d.LIST_EMPTY||k===d.LIST_8||k===d.LIST_16)y=r(k);else{switch(k){case d.BINARY_8:r=q(h());break;case d.BINARY_20:r=q(z());break;case d.BINARY_32:r=q(w(4));break;default:r=p(k)}y=r}return{tag:x,attrs:C,content:y}};exports.decodeDecompressedBinaryNode=decodeDecompressedBinaryNode;const decodeBinaryNode=b=>{b=(0,exports.decompressingIfRequired)(b);return(0,exports.decodeDecompressedBinaryNode)(b,constants)};
exports.decodeBinaryNode=decodeBinaryNode;
