var __importDefault=this&&this.__importDefault||function(m){return m&&m.__esModule?m:{"default":m}};Object.defineProperty(exports,"__esModule",{value:!0});exports.makeChatsSocket=void 0;
const boom_1=require("@hapi/boom"),WAProto_1=require("../../WAProto"),Defaults_1=require("../Defaults"),Types_1=require("../Types"),Utils_1=require("../Utils"),make_mutex_1=require("../Utils/make-mutex"),process_message_1=__importDefault(require("../Utils/process-message")),WABinary_1=require("../WABinary"),socket_1=require("./socket"),MAX_SYNC_ATTEMPTS=2,makeChatsSocket=m=>{const {logger:l,markOnlineOnConnect:V,fireInitQueries:W,appStateMacVerification:I,shouldIgnoreJid:X,shouldSyncHistoryMessage:Y}=
m,J=(0,socket_1.makeSocket)(m),{ev:p,ws:E,authState:e,generateMessageTag:F,sendNode:B,query:r,onUnexpectedError:K}=J;let G,L=!1,C=!1;const M=(0,make_mutex_1.makeMutex)(),D=async a=>{({[a]:a}=await e.keys.get("app-state-sync-key",[a]));return a},N=async(a=!1)=>{if(!G||a)({content:a}=await r({tag:"iq",attrs:{xmlns:"privacy",to:WABinary_1.S_WHATSAPP_NET,type:"get"},content:[{tag:"privacy",attrs:{}}]})),G=(0,WABinary_1.reduceBinaryNodeToDictionary)(null===a||void 0===a?void 0:a[0],"category");return G},
y=async(a,b)=>{await r({tag:"iq",attrs:{xmlns:"privacy",to:WABinary_1.S_WHATSAPP_NET,type:"set"},content:[{tag:"privacy",attrs:{},content:[{tag:"category",attrs:{name:a,value:b}}]}]})},O=async(a,b)=>{a=await r({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"get",xmlns:"usync"},content:[{tag:"usync",attrs:{sid:F(),mode:"query",last:"true",index:"0",context:"interactive"},content:[{tag:"query",attrs:{},content:[b]},{tag:"list",attrs:{},content:a}]}]});a=(0,WABinary_1.getBinaryNodeChild)(a,"usync");
a=(0,WABinary_1.getBinaryNodeChild)(a,"list");return(0,WABinary_1.getBinaryNodeChildren)(a,"user")},P=async()=>{var a=await r({tag:"iq",attrs:{xmlns:"blocklist",to:WABinary_1.S_WHATSAPP_NET,type:"get"}});a=(0,WABinary_1.getBinaryNodeChild)(a,"list");return(0,WABinary_1.getBinaryNodeChildren)(a,"item").map(b=>b.attrs.jid)},Q=async(a,b)=>{l.info({fromTimestamp:b},"clean dirty bits "+a);await B({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"urn:xmpp:whatsapp:dirty",id:F()},content:[{tag:"clean",
attrs:{type:a,...(b?{timestamp:b.toString()}:null)}}]})},R=a=>({onMutation(b){(0,Utils_1.processSyncAction)(b,p,e.creds.me,a?{accountSettings:e.creds.accountSettings}:void 0,l)}}),H=p.createBufferedFunction(async(a,b)=>{const c={},f={};await e.keys.transaction(async()=>{var g;const h=new Set(a),k={};for(;h.size;){const w={};var n=[];for(const t of h){var d=(await e.keys.get("app-state-sync-version",[t]))[t];d?"undefined"===typeof c[t]&&(c[t]=d.version):d=(0,Utils_1.newLTHashState)();w[t]=d;l.info(`resyncing ${t} from v${d.version}`);
n.push({tag:"collection",attrs:{name:t,version:d.version.toString(),return_snapshot:(!d.version).toString()}})}n=await r({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,xmlns:"w:sync:app:state",type:"set"},content:[{tag:"sync",attrs:{},content:n}]});n=await (0,Utils_1.extractSyncdPatches)(n,null===m||void 0===m?void 0:m.options);for(const t in n){d=t;const {patches:z,hasMorePatches:A,snapshot:u}=n[d];try{if(u){const {state:q,mutationMap:v}=await (0,Utils_1.decodeSyncdSnapshot)(d,u,D,c[d],I.snapshot);
w[d]=q;Object.assign(f,v);l.info(`restored state of ${d} from snapshot to v${q.version} with mutations`);await e.keys.set({"app-state-sync-version":{[d]:q}})}if(z.length){const {state:q,mutationMap:v}=await (0,Utils_1.decodePatches)(d,z,w[d],D,m.options,c[d],l,I.patch);await e.keys.set({"app-state-sync-version":{[d]:q}});l.info(`synced ${d} to v${q.version}`);c[d]=q.version;Object.assign(f,v)}A?l.info(`${d} has more patches...`):h.delete(d)}catch(q){const v=k[d]>=MAX_SYNC_ATTEMPTS||404===(null===
(g=q.output)||void 0===g?void 0:g.statusCode)||"TypeError"===q.name;l.info({name:d,error:q.stack},`failed to sync state from version${v?"":", removing and trying from scratch"}`);await e.keys.set({"app-state-sync-version":{[d]:null}});k[d]=(k[d]||0)+1;v&&h.delete(d)}}}});({onMutation:b}=R(b));for(const g in f)b(f[g])}),S=async(a,b)=>{const c=e.creds.me;"available"===a||"unavailable"===a?c.name?(p.emit("connection.update",{isOnline:"available"===a}),await B({tag:"presence",attrs:{name:c.name,type:a}})):
l.warn("no name present, ignoring presence update request..."):await B({tag:"chatstate",attrs:{from:c.id,to:b},content:[{tag:"recording"===a?"composing":a,attrs:"recording"===a?{media:"audio"}:{}}]})},T=({tag:a,attrs:b,content:c})=>{var f;let g;const h=b.from,k=b.participant||b.from;X(h)&&"@s.whatsapp.net"!==h||("presence"===a?g={lastKnownPresence:"unavailable"===b.type?"unavailable":"available",lastSeen:b.last&&"deny"!==b.last?+b.last:void 0}:Array.isArray(c)?([a]=c,b=a.tag,"paused"===b&&(b="available"),
"audio"===(null===(f=a.attrs)||void 0===f?void 0:f.media)&&(b="recording"),g={lastKnownPresence:b}):l.error({tag:a,attrs:b,content:c},"recv invalid presence node"),g&&p.emit("presence.update",{id:h,presences:{[k]:g}}))},U=async a=>{const b=a.type,c=e.creds.myAppStateKeyId;if(!c)throw new boom_1.Boom("App state key not present!",{statusCode:400});let f,g;await M.mutex(async()=>{await e.keys.transaction(async()=>{l.debug({patch:a},"applying app patch");await H([b],!1);var {[b]:h}=await e.keys.get("app-state-sync-version",
[b]);f=h||(0,Utils_1.newLTHashState)();g=await (0,Utils_1.encodeSyncdPatch)(a,c,f,D);const {patch:k,state:n}=g;h={tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"w:sync:app:state"},content:[{tag:"sync",attrs:{},content:[{tag:"collection",attrs:{name:b,version:(n.version-1).toString(),return_snapshot:"false"},content:[{tag:"patch",attrs:{},content:WAProto_1.proto.SyncdPatch.encode(k).finish()}]}]}]};await r(h);await e.keys.set({"app-state-sync-version":{[b]:n}})})});if(m.emitOwnEvents){const {onMutation:h}=
R(!1),{mutationMap:k}=await (0,Utils_1.decodePatches)(b,[{...g.patch,version:{version:g.state.version}}],f,D,m.options,void 0,l);for(const n in k)h(k[n])}},Z=async()=>{var a,b,c=await r({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,xmlns:"w",type:"get"},content:[{tag:"props",attrs:{protocol:"2",hash:(null===(a=null===e||void 0===e?void 0:e.creds)||void 0===a?void 0:a.lastPropHash)||""}}]});a=(0,WABinary_1.getBinaryNodeChild)(c,"props");c={};a&&(e.creds.lastPropHash=null===(b=null===a||void 0===a?
void 0:a.attrs)||void 0===b?void 0:b.hash,p.emit("creds.update",e.creds),c=(0,WABinary_1.reduceBinaryNodeToDictionary)(a,"prop"));l.debug("fetched props");return c},x=(a,b)=>{a=(0,Utils_1.chatModificationToAppPatch)(a,b);return U(a)},aa=async()=>{await Promise.all([Z(),P(),N()])},ba=p.createBufferedFunction(async(a,b)=>{async function c(){e.creds.accountSyncCounter||(l.info("doing initial app state sync"),await H(Types_1.ALL_WA_PATCH_NAMES,!0),p.emit("creds.update",{accountSyncCounter:(e.creds.accountSyncCounter||
0)+1}),L&&(l.debug("flushing with app state sync"),p.flush()))}var f,g,h;p.emit("messages.upsert",{messages:[a],type:b});a.pushName&&(b=a.key.fromMe?e.creds.me.id:a.key.participant||a.key.remoteJid,b=(0,WABinary_1.jidNormalizedUser)(b),a.key.fromMe||p.emit("contacts.update",[{id:b,notify:a.pushName,verifiedName:a.verifiedBizName}]),a.key.fromMe&&a.pushName&&(null===(f=e.creds.me)||void 0===f?void 0:f.name)!==a.pushName&&p.emit("creds.update",{me:{...e.creds.me,name:a.pushName}}));const k=(0,Utils_1.getHistoryMsg)(a.message);
f=k?Y(k)&&Defaults_1.PROCESSABLE_HISTORY_TYPES.includes(k.syncType):!1;k&&!e.creds.myAppStateKeyId&&(l.warn("skipping app state sync, as myAppStateKeyId is not set"),C=!0);await Promise.all([(async()=>{k&&e.creds.myAppStateKeyId&&(C=!1,await c())})(),(0,process_message_1.default)(a,{shouldProcessHistoryMsg:f,ev:p,creds:e.creds,keyStore:e.keys,logger:l,options:m.options,getMessage:m.getMessage})]);(null===(h=null===(g=a.message)||void 0===g?void 0:g.protocolMessage)||void 0===h?0:h.appStateSyncKeyShare)&&
C&&(await c(),C=!1)});E.on("CB:presence",T);E.on("CB:chatstate",T);E.on("CB:ib,,dirty",async a=>{const {attrs:b}=(0,WABinary_1.getBinaryNodeChild)(a,"dirty");switch(b.type){case "account_sync":b.timestamp&&({lastAccountSyncTimestamp:a}=e.creds,a&&await Q("account_sync",a),a=+b.timestamp,p.emit("creds.update",{lastAccountSyncTimestamp:a}));break;case "groups":break;default:l.info({node:a},"received unknown sync")}});p.on("connection.update",({connection:a,receivedPendingNotifications:b})=>{var c;"open"===
a&&(W&&aa().catch(f=>K(f,"init queries")),S(V?"available":"unavailable").catch(f=>K(f,"presence update requests")));!b||null!==(c=e.creds)&&void 0!==c&&c.myAppStateKeyId||m.mobile||(p.buffer(),L=!0)});return{...J,processingMutex:M,fetchPrivacySettings:N,upsertMessage:ba,appPatch:U,sendPresenceUpdate:S,presenceSubscribe:(a,b)=>B({tag:"presence",attrs:{to:a,id:F(),type:"subscribe"},content:b?[{tag:"tctoken",attrs:{},content:b}]:void 0}),profilePictureUrl:async(a,b="preview",c)=>{var f;a=(0,WABinary_1.jidNormalizedUser)(a);
a=await r({tag:"iq",attrs:{target:a,to:WABinary_1.S_WHATSAPP_NET,type:"get",xmlns:"w:profile:picture"},content:[{tag:"picture",attrs:{type:b,query:"url"}}]},c);a=(0,WABinary_1.getBinaryNodeChild)(a,"picture");return null===(f=null===a||void 0===a?void 0:a.attrs)||void 0===f?void 0:f.url},onWhatsApp:async(...a)=>{a=a.map(b=>({tag:"user",attrs:{},content:[{tag:"contact",attrs:{},content:`+${b.replace("+","")}`}]}));return(await O(a,{tag:"contact",attrs:{}})).map(b=>{const c=(0,WABinary_1.getBinaryNodeChild)(b,
"contact");return{exists:"in"===(null===c||void 0===c?void 0:c.attrs.type),jid:b.attrs.jid}}).filter(b=>b.exists)},fetchBlocklist:P,fetchStatus:async a=>{[a]=await O([{tag:"user",attrs:{jid:a}}],{tag:"status",attrs:{}});if(a)return a=(0,WABinary_1.getBinaryNodeChild)(a,"status"),{status:null===a||void 0===a?void 0:a.content.toString(),setAt:new Date(1E3*+((null===a||void 0===a?void 0:a.attrs.t)||0))}},updateProfilePicture:async(a,b)=>{let c;if(!a)throw new boom_1.Boom("Illegal no-jid profile update. Please specify either your ID or the ID of the chat you wish to update");
(0,WABinary_1.jidNormalizedUser)(a)!==(0,WABinary_1.jidNormalizedUser)(e.creds.me.id)&&(c=(0,WABinary_1.jidNormalizedUser)(a));({img:a}=await (0,Utils_1.generateProfilePicture)(b));await r({tag:"iq",attrs:{target:c,to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"w:profile:picture"},content:[{tag:"picture",attrs:{type:"image"},content:a}]})},removeProfilePicture:async a=>{let b;if(!a)throw new boom_1.Boom("Illegal no-jid profile update. Please specify either your ID or the ID of the chat you wish to update");
(0,WABinary_1.jidNormalizedUser)(a)!==(0,WABinary_1.jidNormalizedUser)(e.creds.me.id)&&(b=(0,WABinary_1.jidNormalizedUser)(a));await r({tag:"iq",attrs:{target:b,to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"w:profile:picture"}})},updateProfileStatus:async a=>{await r({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"status"},content:[{tag:"status",attrs:{},content:Buffer.from(a,"utf-8")}]})},updateProfileName:async a=>{await x({pushNameSetting:a},"")},updateBlockStatus:async(a,b)=>
{await r({tag:"iq",attrs:{xmlns:"blocklist",to:WABinary_1.S_WHATSAPP_NET,type:"set"},content:[{tag:"item",attrs:{action:b,jid:a}}]})},updateLastSeenPrivacy:async a=>{await y("last",a)},updateOnlinePrivacy:async a=>{await y("online",a)},updateProfilePicturePrivacy:async a=>{await y("profile",a)},updateStatusPrivacy:async a=>{await y("status",a)},updateReadReceiptsPrivacy:async a=>{await y("readreceipts",a)},updateGroupsAddPrivacy:async a=>{await y("groupadd",a)},updateDefaultDisappearingMode:async a=>
{await r({tag:"iq",attrs:{xmlns:"disappearing_mode",to:WABinary_1.S_WHATSAPP_NET,type:"set"},content:[{tag:"disappearing_mode",attrs:{duration:a.toString()}}]})},getBusinessProfile:async a=>{var b,c,f,g,h,k,n;a=await r({tag:"iq",attrs:{to:"s.whatsapp.net",xmlns:"w:biz",type:"get"},content:[{tag:"business_profile",attrs:{v:"244"},content:[{tag:"profile",attrs:{jid:a}}]}]});a=(0,WABinary_1.getBinaryNodeChild)(a,"business_profile");if(a=(0,WABinary_1.getBinaryNodeChild)(a,"profile")){const w=(0,WABinary_1.getBinaryNodeChild)(a,
"address"),t=(0,WABinary_1.getBinaryNodeChild)(a,"description");var d=(0,WABinary_1.getBinaryNodeChild)(a,"website");const z=(0,WABinary_1.getBinaryNodeChild)(a,"email"),A=(0,WABinary_1.getBinaryNodeChild)((0,WABinary_1.getBinaryNodeChild)(a,"categories"),"category"),u=(0,WABinary_1.getBinaryNodeChild)(a,"business_hours"),q=u?(0,WABinary_1.getBinaryNodeChildren)(u,"business_hours_config"):void 0;d=null===(b=null===d||void 0===d?void 0:d.content)||void 0===b?void 0:b.toString();return{wid:null===(c=
a.attrs)||void 0===c?void 0:c.jid,address:null===(f=null===w||void 0===w?void 0:w.content)||void 0===f?void 0:f.toString(),description:(null===(g=null===t||void 0===t?void 0:t.content)||void 0===g?void 0:g.toString())||"",website:d?[d]:[],email:null===(h=null===z||void 0===z?void 0:z.content)||void 0===h?void 0:h.toString(),category:null===(k=null===A||void 0===A?void 0:A.content)||void 0===k?void 0:k.toString(),business_hours:{timezone:null===(n=null===u||void 0===u?void 0:u.attrs)||void 0===n?void 0:
n.timezone,business_config:null===q||void 0===q?void 0:q.map(({attrs:v})=>v)}}}},resyncAppState:H,chatModify:x,cleanDirtyBits:Q,addChatLabel:(a,b)=>x({addChatLabel:{labelId:b}},a),removeChatLabel:(a,b)=>x({removeChatLabel:{labelId:b}},a),addMessageLabel:(a,b,c)=>x({addMessageLabel:{messageId:b,labelId:c}},a),removeMessageLabel:(a,b,c)=>x({removeMessageLabel:{messageId:b,labelId:c}},a),star:(a,b,c)=>x({star:{messages:b,star:c}},a)}};exports.makeChatsSocket=makeChatsSocket;
