var __importDefault=this&&this.__importDefault||function(r){return r&&r.__esModule?r:{"default":r}};Object.defineProperty(exports,"__esModule",{value:!0});exports.makeMessagesRecvSocket=void 0;
const node_cache_1=__importDefault(require("@cacheable/node-cache")),boom_1=require("@hapi/boom"),crypto_1=require("crypto"),WAProto_1=require("../../WAProto"),Defaults_1=require("../Defaults"),Types_1=require("../Types"),Utils_1=require("../Utils"),make_mutex_1=require("../Utils/make-mutex"),WABinary_1=require("../WABinary"),groups_1=require("./groups"),messages_send_1=require("./messages-send"),makeMessagesRecvSocket=r=>{async function W(a){a=z(a);var b=a.slice(0,32);b=await (0,Utils_1.derivePairingCodeKey)(h.creds.pairingCode,
b);const c=a.slice(32,48);a=a.slice(48,80);return(0,Utils_1.aesDecryptCTR)(a,b,c)}function z(a){if(void 0===a)throw new boom_1.Boom("Invalid buffer",{statusCode:400});return a instanceof Buffer?a:Buffer.from(a)}const {logger:l,retryRequestDelayMs:K,maxMsgRetryCount:L,getMessage:X,shouldIgnoreJid:D}=r,E=(0,messages_send_1.makeMessagesSocket)(r),{ev:p,authState:h,ws:u,processingMutex:F,signalRepository:Y,query:M,upsertMessage:G,resyncAppState:Z,onUnexpectedError:A,assertSessions:aa,sendNode:N,relayMessage:ba,
sendReceipt:O,uploadPreKeys:ca,sendPeerDataOperationMessage:P}=E,da=(0,make_mutex_1.makeMutex)(),x=r.msgRetryCounterCache||new node_cache_1.default({stdTTL:Defaults_1.DEFAULT_CACHE_TTLS.MSG_RETRY,useClones:!1}),H=r.callOfferCache||new node_cache_1.default({stdTTL:Defaults_1.DEFAULT_CACHE_TTLS.CALL_OFFER,useClones:!1}),v=r.placeholderResendCache||new node_cache_1.default({stdTTL:Defaults_1.DEFAULT_CACHE_TTLS.MSG_RETRY,useClones:!1});let I=!1;const t=async({tag:a,attrs:b,content:c},e)=>{const f={tag:"ack",
attrs:{id:b.id,to:b.from,class:a}};e&&(f.attrs.error=e.toString());b.participant&&(f.attrs.participant=b.participant);b.recipient&&(f.attrs.recipient=b.recipient);b.type&&("message"!==a||(0,WABinary_1.getBinaryNodeChild)({tag:a,attrs:b,content:c},"unavailable")||0!==e)&&(f.attrs.type=b.type);"message"===a&&(0,WABinary_1.getBinaryNodeChild)({tag:a,attrs:b,content:c},"unavailable")&&(f.attrs.from=h.creds.me.id);l.debug({recv:{tag:a,attrs:b},sent:f.attrs},"sent ack");await N(f)},R=async(a,b=!1)=>{var {fullMessage:c}=
(0,Utils_1.decodeMessageNode)(a,h.creds.me.id,h.creds.me.lid||"");({key:c}=c);const e=c.id,f=`${e}:${null===c||void 0===c?void 0:c.participant}`;let d=x.get(f)||0;if(d>=L)l.debug({retryCount:d,msgId:e},"reached retry limit, clearing"),x.del(f);else{d+=1;x.set(f,d);var {account:n,signedPreKey:k,signedIdentityKey:g}=h.creds;1===d&&(c=await J(c),l.debug(`sendRetryRequest: requested placeholder resend for message ${c}`));var m=(0,Utils_1.encodeSignedDeviceIdentity)(n,!0);await h.keys.transaction(async()=>
{const q={tag:"receipt",attrs:{id:e,type:"retry",to:a.attrs.from},content:[{tag:"retry",attrs:{count:d.toString(),id:a.attrs.id,t:a.attrs.t,v:"1"}},{tag:"registration",attrs:{},content:(0,Utils_1.encodeBigEndian)(h.creds.registrationId)}]};a.attrs.recipient&&(q.attrs.recipient=a.attrs.recipient);a.attrs.participant&&(q.attrs.participant=a.attrs.participant);if(1<d||b){const {update:w,preKeys:y}=await (0,Utils_1.getNextPreKeys)(h,1),[Q]=Object.keys(y),ea=y[+Q];q.content.push({tag:"keys",attrs:{},content:[{tag:"type",
attrs:{},content:Buffer.from(Defaults_1.KEY_BUNDLE_TYPE)},{tag:"identity",attrs:{},content:g.public},(0,Utils_1.xmppPreKey)(ea,+Q),(0,Utils_1.xmppSignedPreKey)(k),{tag:"device-identity",attrs:{},content:m}]});p.emit("creds.update",w)}await N(q);l.info({msgAttrs:a.attrs,retryCount:d},"sent retry receipt")})}},fa=async a=>{var b=a.attrs.from;b===WABinary_1.S_WHATSAPP_NET?(a=+(0,WABinary_1.getBinaryNodeChild)(a,"count").attrs.value,b=a<Defaults_1.MIN_PREKEY_COUNT,l.debug({count:a,shouldUploadMorePreKeys:b},
"recv pre-key count"),b&&await ca()):(0,WABinary_1.getBinaryNodeChild)(a,"identity")?l.info({jid:b},"identity changed"):l.info({node:a},"unknown encrypt notification")},ha=(a,b,c)=>{var e,f,d;const n=(null===(f=null===(e=(0,WABinary_1.getBinaryNodeChild)(b,"participant"))||void 0===e?void 0:e.attrs)||void 0===f?void 0:f.jid)||a;switch(null===b||void 0===b?void 0:b.tag){case "create":b=(0,groups_1.extractGroupMetadata)(b);c.messageStubType=Types_1.WAMessageStubType.GROUP_CREATE;c.messageStubParameters=
[b.subject];c.key={participant:b.owner};p.emit("chats.upsert",[{id:b.id,name:b.subject,conversationTimestamp:b.creation}]);p.emit("groups.upsert",[{...b,author:a}]);break;case "ephemeral":case "not_ephemeral":c.message={protocolMessage:{type:WAProto_1.proto.Message.ProtocolMessage.Type.EPHEMERAL_SETTING,ephemeralExpiration:+(b.attrs.expiration||0)}};break;case "modify":a=(0,WABinary_1.getBinaryNodeChildren)(b,"participant").map(g=>g.attrs.jid);c.messageStubParameters=a||[];c.messageStubType=Types_1.WAMessageStubType.GROUP_PARTICIPANT_CHANGE_NUMBER;
break;case "promote":case "demote":case "remove":case "add":case "leave":var k=`GROUP_PARTICIPANT_${b.tag.toUpperCase()}`;c.messageStubType=Types_1.WAMessageStubType[k];k=(0,WABinary_1.getBinaryNodeChildren)(b,"participant").map(g=>g.attrs.jid);1===k.length&&(0,WABinary_1.areJidsSameUser)(k[0],a)&&"remove"===b.tag&&(c.messageStubType=Types_1.WAMessageStubType.GROUP_PARTICIPANT_LEAVE);c.messageStubParameters=k;break;case "subject":c.messageStubType=Types_1.WAMessageStubType.GROUP_CHANGE_SUBJECT;c.messageStubParameters=
[b.attrs.subject];break;case "description":a=null===(d=null===(k=(0,WABinary_1.getBinaryNodeChild)(b,"body"))||void 0===k?void 0:k.content)||void 0===d?void 0:d.toString();c.messageStubType=Types_1.WAMessageStubType.GROUP_CHANGE_DESCRIPTION;c.messageStubParameters=a?[a]:void 0;break;case "announcement":case "not_announcement":c.messageStubType=Types_1.WAMessageStubType.GROUP_CHANGE_ANNOUNCE;c.messageStubParameters=["announcement"===b.tag?"on":"off"];break;case "locked":case "unlocked":c.messageStubType=
Types_1.WAMessageStubType.GROUP_CHANGE_RESTRICT;c.messageStubParameters=["locked"===b.tag?"on":"off"];break;case "invite":c.messageStubType=Types_1.WAMessageStubType.GROUP_CHANGE_INVITE_LINK;c.messageStubParameters=[b.attrs.code];break;case "member_add_mode":if(a=b.content)c.messageStubType=Types_1.WAMessageStubType.GROUP_MEMBER_ADD_MODE,c.messageStubParameters=[a.toString()];break;case "membership_approval_mode":if(a=(0,WABinary_1.getBinaryNodeChild)(b,"group_join"))c.messageStubType=Types_1.WAMessageStubType.GROUP_MEMBERSHIP_JOIN_APPROVAL_MODE,
c.messageStubParameters=[a.attrs.state];break;case "created_membership_requests":c.messageStubType=Types_1.WAMessageStubType.GROUP_MEMBERSHIP_JOIN_APPROVAL_REQUEST_NON_ADMIN_ADD;c.messageStubParameters=[n,"created",b.attrs.request_method];break;case "revoked_membership_requests":a=(0,WABinary_1.areJidsSameUser)(n,a),c.messageStubType=Types_1.WAMessageStubType.GROUP_MEMBERSHIP_JOIN_APPROVAL_REQUEST_NON_ADMIN_ADD,c.messageStubParameters=[n,a?"revoked":"rejected"]}},ia=async a=>{var b,c,e;const f={};
var [d]=(0,WABinary_1.getAllBinaryNodeChildren)(a),n=a.attrs.type,k=(0,WABinary_1.jidNormalizedUser)(a.attrs.from);switch(n){case "privacy_token":a=(0,WABinary_1.getBinaryNodeChildren)(d,"token");for(const {attrs:m,content:q}of a)a=m.jid,p.emit("chats.update",[{id:a,tcToken:q}]),l.debug({jid:a},"got privacy token update");break;case "w:gp2":ha(a.attrs.participant,d,f);break;case "mediaretry":a=(0,Utils_1.decodeMediaRetryNode)(a);p.emit("messages.media-update",[a]);break;case "encrypt":await fa(a);
break;case "devices":a=(0,WABinary_1.getBinaryNodeChildren)(d,"device");(0,WABinary_1.areJidsSameUser)(d.attrs.jid,h.creds.me.id)&&(a=a.map(m=>m.attrs.jid),l.info({deviceJids:a},"got my own devices"));break;case "server_sync":(a=(0,WABinary_1.getBinaryNodeChild)(a,"collection"))&&await Z([a.attrs.name],!1);break;case "picture":d=(0,WABinary_1.getBinaryNodeChild)(a,"set");var g=(0,WABinary_1.getBinaryNodeChild)(a,"delete");p.emit("contacts.update",[{id:(0,WABinary_1.jidNormalizedUser)(null===(b=null===
a||void 0===a?void 0:a.attrs)||void 0===b?void 0:b.from)||(null===(e=null===(c=d||g)||void 0===c?void 0:c.attrs)||void 0===e?void 0:e.hash)||"",imgUrl:d?"changed":"removed"}]);(0,WABinary_1.isJidGroup)(k)&&(a=d||g,f.messageStubType=Types_1.WAMessageStubType.GROUP_CHANGE_ICON,d&&(f.messageStubParameters=[d.attrs.id]),f.participant=null===a||void 0===a?void 0:a.attrs.author,f.key={...(f.key||{}),participant:null===d||void 0===d?void 0:d.attrs.author});break;case "account_sync":if("disappearing_mode"===
d.tag)a=+d.attrs.duration,b=+d.attrs.t,l.info({newDuration:a},"updated account disappearing mode"),p.emit("creds.update",{accountSettings:{...h.creds.accountSettings,defaultDisappearingMode:{ephemeralExpiration:a,ephemeralSettingTimestamp:b}}});else if("blocklist"===d.tag){a=(0,WABinary_1.getBinaryNodeChildren)(d,"item");for({attrs:g}of a)p.emit("blocklist.update",{blocklist:[g.jid],type:"block"===g.action?"add":"remove"})}break;case "link_code_companion_reg":c=(0,WABinary_1.getBinaryNodeChild)(a,
"link_code_companion_reg"),a=z((0,WABinary_1.getBinaryNodeChildBuffer)(c,"link_code_pairing_ref")),b=z((0,WABinary_1.getBinaryNodeChildBuffer)(c,"primary_identity_pub")),c=z((0,WABinary_1.getBinaryNodeChildBuffer)(c,"link_code_pairing_wrapped_primary_ephemeral_pub")),c=await W(c),c=Utils_1.Curve.sharedKey(h.creds.pairingEphemeralKeyPair.private,c),e=(0,crypto_1.randomBytes)(32),d=(0,crypto_1.randomBytes)(32),g=await (0,Utils_1.hkdf)(c,32,{salt:d,info:"link_code_pairing_key_bundle_encryption_key"}),
n=Buffer.concat([Buffer.from(h.creds.signedIdentityKey.public),b,e]),k=(0,crypto_1.randomBytes)(12),g=(0,Utils_1.aesEncryptGCM)(n,g,k,Buffer.alloc(0)),d=Buffer.concat([d,k,g]),b=Utils_1.Curve.sharedKey(h.creds.signedIdentityKey.private,b),b=Buffer.concat([c,b,e]),h.creds.advSecretKey=(await (0,Utils_1.hkdf)(b,32,{info:"adv_secret"})).toString("base64"),await M({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"set",id:E.generateMessageTag(),xmlns:"md"},content:[{tag:"link_code_companion_reg",attrs:{jid:h.creds.me.id,
stage:"companion_finish"},content:[{tag:"link_code_pairing_wrapped_key_bundle",attrs:{},content:d},{tag:"companion_identity_public",attrs:{},content:h.creds.signedIdentityKey.public},{tag:"link_code_pairing_ref",attrs:{},content:a}]}]}),h.creds.registered=!0,p.emit("creds.update",h.creds)}if(Object.keys(f).length)return f},ja=(a,b)=>{a=`${a}:${b}`;b=(x.get(a)||0)+1;x.set(a,b)},ka=async(a,b,c)=>{var e;const f=await Promise.all(b.map(g=>X({...a,id:g}))),d=a.remoteJid,n=a.participant||d,k=!(null===(e=
(0,WABinary_1.jidDecode)(n))||void 0===e?0:e.device);await aa([n],!0);(0,WABinary_1.isJidGroup)(d)&&await h.keys.set({"sender-key-memory":{[d]:null}});l.debug({participant:n,sendToAll:k},"forced new session for retry recp");for(const [g,m]of f.entries())m?(ja(b[g],n),e={messageId:b[g]},k?e.useUserDevicesCache=!1:e.participant={jid:n,count:+c.attrs.count},await ba(a.remoteJid,m,e)):l.debug({jid:a.remoteJid,id:b[g]},"recv retry request, but message not available")},S=async a=>{var b,c;const {attrs:e,
content:f}=a,d=e.from.includes("lid"),n=(0,WABinary_1.areJidsSameUser)(e.participant||e.from,d?null===(b=h.creds.me)||void 0===b?void 0:b.lid:null===(c=h.creds.me)||void 0===c?void 0:c.id),k=!n||(0,WABinary_1.isJidGroup)(e.from)?e.from:e.recipient,g={remoteJid:k,id:"",fromMe:!e.recipient||"retry"===e.type&&n,participant:e.participant};if(D(k)&&"@s.whatsapp.net"!==k)l.debug({remoteJid:k},"ignoring receipt from jid"),await t(a);else{var m=[e.id];Array.isArray(f)&&(b=(0,WABinary_1.getBinaryNodeChildren)(f[0],
"item"),m.push(...b.map(q=>q.attrs.id)));try{await Promise.all([F.mutex(async()=>{const q=(0,Utils_1.getStatusFromReceiptType)(e.type);if("undefined"!==typeof q&&(q>=WAProto_1.proto.WebMessageInfo.Status.SERVER_ACK||!n))if((0,WABinary_1.isJidGroup)(k)||(0,WABinary_1.isJidStatusBroadcast)(k)){if(e.participant){const w=q===WAProto_1.proto.WebMessageInfo.Status.DELIVERY_ACK?"receiptTimestamp":"readTimestamp";p.emit("message-receipt.update",m.map(y=>({key:{...g,id:y},receipt:{userJid:(0,WABinary_1.jidNormalizedUser)(e.participant),
[w]:+e.t}})))}}else p.emit("messages.update",m.map(w=>({key:{...g,id:w},update:{status:q}})));if("retry"===e.type){g.participant=g.participant||e.from;const w=(0,WABinary_1.getBinaryNodeChild)(a,"retry");if((x.get(`${m[0]}:${g.participant}`)||0)<L)if(g.fromMe)try{l.debug({attrs:e,key:g},"recv retry request"),await ka(g,m,w)}catch(y){l.error({key:g,ids:m,trace:y.stack},"error in sending message again")}else l.info({attrs:e,key:g},"recv retry for not fromMe message");else l.info({attrs:e,key:g},"will not send message again, as sent too many times")}})])}finally{await t(a)}}},
T=async a=>{const b=a.attrs.from;if(D(b)&&"@s.whatsapp.net"!==b)l.debug({remoteJid:b,id:a.attrs.id},"ignored notification"),await t(a);else try{await Promise.all([F.mutex(async()=>{var c;const e=await ia(a);if(e){const f=(0,WABinary_1.areJidsSameUser)(a.attrs.participant||b,h.creds.me.id);e.key={remoteJid:b,fromMe:f,participant:a.attrs.participant,id:a.attrs.id,...(e.key||{})};null!==(c=e.participant)&&void 0!==c?c:e.participant=a.attrs.participant;e.messageTimestamp=+a.attrs.t;c=WAProto_1.proto.WebMessageInfo.fromObject(e);
await G(c,"append")}})])}finally{await t(a)}},U=async a=>{var b,c,e;if(D(a.attrs.from)&&"@s.whatsapp.net"!==a.attrs.from)l.debug({key:a.attrs.key},"ignored message"),await t(a);else{if((0,WABinary_1.getBinaryNodeChild)(a,"unavailable")&&!(0,WABinary_1.getBinaryNodeChild)(a,"enc")){await t(a);({key:f}=(0,Utils_1.decodeMessageNode)(a,h.creds.me.id,h.creds.me.lid||"").fullMessage);var f=await J(f);if("RESOLVED"===f)return;l.debug("received unavailable message, acked and requested resend from phone")}else v.get(a.attrs.id)&&
v.del(a.attrs.id);var {fullMessage:d,category:n,author:k,decrypt:g}=(0,Utils_1.decryptMessageNode)(a,h.creds.me.id,h.creds.me.lid||"",Y,l);f&&(null===(b=null===d||void 0===d?void 0:d.messageStubParameters)||void 0===b?void 0:b[0])===Utils_1.NO_MESSAGE_FOUND_ERROR_TEXT&&(d.messageStubParameters=[Utils_1.NO_MESSAGE_FOUND_ERROR_TEXT,f]);(null===(e=null===(c=d.message)||void 0===c?void 0:c.protocolMessage)||void 0===e?void 0:e.type)===WAProto_1.proto.Message.ProtocolMessage.Type.SHARE_PHONE_NUMBER&&a.attrs.sender_pn&&
p.emit("chats.phoneNumberShare",{lid:a.attrs.from,jid:a.attrs.sender_pn});try{await Promise.all([F.mutex(async()=>{var m;await g();if(d.messageStubType===WAProto_1.proto.WebMessageInfo.StubType.CIPHERTEXT){if((null===(m=null===d||void 0===d?void 0:d.messageStubParameters)||void 0===m?void 0:m[0])===Utils_1.MISSING_KEYS_ERROR_TEXT)return t(a,Utils_1.NACK_REASONS.ParsingError);da.mutex(async()=>{if(u.isOpen){if(!(0,WABinary_1.getBinaryNodeChild)(a,"unavailable")){var q=(0,WABinary_1.getBinaryNodeChild)(a,
"enc");await R(a,!q);K&&await (0,Utils_1.delay)(K)}}else l.debug({node:a},"connection closed, ignoring retry req")})}else{m=void 0;let q=d.key.participant;"peer"===n?m="peer_msg":d.key.fromMe?(m="sender",(0,WABinary_1.isJidUser)(d.key.remoteJid)&&(q=k)):I||(m="inactive");await O(d.key.remoteJid,q,[d.key.id],m);(0,Utils_1.getHistoryMsg)(d.message)&&(m=(0,WABinary_1.jidNormalizedUser)(d.key.remoteJid),await O(m,void 0,[d.key.id],"hist_sync"))}(0,Utils_1.cleanMessage)(d,h.creds.me.id);await t(a);await G(d,
a.attrs.offline?"append":"notify")})])}catch(m){l.error({error:m,node:a},"error in handling message")}}},J=async a=>{var b;if(null===(b=h.creds.me)||void 0===b||!b.id)throw new boom_1.Boom("Not authenticated");if(v.get(null===a||void 0===a?void 0:a.id))l.debug({messageKey:a},"already requested resend");else{v.set(null===a||void 0===a?void 0:a.id,!0);await (0,Utils_1.delay)(5E3);if(!v.get(null===a||void 0===a?void 0:a.id))return l.debug({messageKey:a},"message received while resend requested"),"RESOLVED";
b={placeholderMessageResendRequest:[{messageKey:a}],peerDataOperationRequestType:WAProto_1.proto.Message.PeerDataOperationRequestType.PLACEHOLDER_MESSAGE_RESEND};setTimeout(()=>{v.get(null===a||void 0===a?void 0:a.id)&&(l.debug({messageKey:a},"PDO message without response after 15 seconds. Phone possibly offline"),v.del(null===a||void 0===a?void 0:a.id))},15E3);return P(b)}},V=async a=>{var {attrs:b}=a,[c]=(0,WABinary_1.getAllBinaryNodeChildren)(a);const e=c.attrs["call-id"],f=c.attrs.from||c.attrs["call-creator"],
d=(0,Utils_1.getCallStatusFromNode)(c);b={chatId:b.from,from:f,id:e,date:new Date(1E3*+b.t),offline:!!b.offline,status:d};"offer"===d&&(b.isVideo=!!(0,WABinary_1.getBinaryNodeChild)(c,"video"),b.isGroup="group"===c.attrs.type||!!c.attrs["group-jid"],b.groupJid=c.attrs["group-jid"],H.set(b.id,b));if(c=H.get(b.id))b.isVideo=c.isVideo,b.isGroup=c.isGroup;"reject"!==d&&"accept"!==d&&"timeout"!==d&&"terminate"!==d||H.del(b.id);p.emit("call",[b]);await t(a)},la=async({attrs:a})=>{const b={remoteJid:a.from,
fromMe:!0,id:a.id};a.error&&(l.warn({attrs:a},"received error in ack"),p.emit("messages.update",[{key:b,update:{status:Types_1.WAMessageStatus.ERROR,messageStubParameters:[a.error]}}]))},B=async(a,b,c)=>{p.buffer();await function(){return c(a,!1).catch(e=>A(e,b))}();p.flush()},C=(()=>{const a=new Map([["message",U],["call",V],["receipt",S],["notification",T]]),b=[];let c=!1;return{enqueue:(e,f)=>{b.push({type:e,node:f});c||(c=!0,(async()=>{for(;b.length&&u.isOpen;){const {type:d,node:n}=b.shift(),
k=a.get(d);k?await k(n):A(Error(`unknown offline node type: ${d}`),"processing offline node")}c=!1})().catch(d=>A(d,"processing offline nodes")))}}})();u.on("CB:message",a=>{a.attrs.offline?C.enqueue("message",a):B(a,"processing message",U)});u.on("CB:call",async a=>{a.attrs.offline?C.enqueue("call",a):B(a,"handling call",V)});u.on("CB:receipt",a=>{a.attrs.offline?C.enqueue("receipt",a):B(a,"handling receipt",S)});u.on("CB:notification",async a=>{a.attrs.offline?C.enqueue("notification",a):B(a,"handling notification",
T)});u.on("CB:ack,class:message",a=>{la(a).catch(b=>A(b,"handling bad ack"))});p.on("call",([a])=>{if("timeout"===a.status||"offer"===a.status&&a.isGroup){var b={key:{remoteJid:a.chatId,id:a.id,fromMe:!1},messageTimestamp:(0,Utils_1.unixTimestampSeconds)(a.date)};"timeout"===a.status?b.messageStubType=a.isGroup?a.isVideo?Types_1.WAMessageStubType.CALL_MISSED_GROUP_VIDEO:Types_1.WAMessageStubType.CALL_MISSED_GROUP_VOICE:a.isVideo?Types_1.WAMessageStubType.CALL_MISSED_VIDEO:Types_1.WAMessageStubType.CALL_MISSED_VOICE:
b.message={call:{callKey:Buffer.from(a.id)}};b=WAProto_1.proto.WebMessageInfo.fromObject(b);G(b,a.offline?"append":"notify")}});p.on("connection.update",({isOnline:a})=>{"undefined"!==typeof a&&(I=a,l.trace(`sendActiveReceipts set to "${I}"`))});return{...E,sendMessageAck:t,sendRetryRequest:R,rejectCall:async(a,b)=>{await M({tag:"call",attrs:{from:h.creds.me.id,to:b},content:[{tag:"reject",attrs:{"call-id":a,"call-creator":b,count:"0"},content:void 0}]})},fetchMessageHistory:async(a,b,c)=>{var e;
if(null===(e=h.creds.me)||void 0===e||!e.id)throw new boom_1.Boom("Not authenticated");return P({historySyncOnDemandRequest:{chatJid:b.remoteJid,oldestMsgFromMe:b.fromMe,oldestMsgId:b.id,oldestMsgTimestampMs:c,onDemandMsgCount:a},peerDataOperationRequestType:WAProto_1.proto.Message.PeerDataOperationRequestType.HISTORY_SYNC_ON_DEMAND})},requestPlaceholderResend:J}};exports.makeMessagesRecvSocket=makeMessagesRecvSocket;
