var __importDefault=this&&this.__importDefault||function(n){return n&&n.__esModule?n:{"default":n}};Object.defineProperty(exports,"__esModule",{value:!0});exports.makeMessagesSocket=void 0;const boom_1=require("@hapi/boom"),node_cache_1=__importDefault(require("node-cache")),WAProto_1=require("../../WAProto"),Defaults_1=require("../Defaults"),Utils_1=require("../Utils"),link_preview_1=require("../Utils/link-preview"),WABinary_1=require("../WABinary"),newsletter_1=require("./newsletter");
var ListType=WAProto_1.proto.Message.ListMessage.ListType;
const makeMessagesSocket=n=>{const {logger:m,linkPreviewImageThumbnailWidth:ma,generateHighQualityLinkPreview:na,options:oa,patchMessageBeforeSending:O}=n,ba=(0,newsletter_1.makeNewsletterSocket)(n),{ev:ca,authState:q,processingMutex:pa,signalRepository:G,upsertMessage:qa,query:L,fetchPrivacySettings:da,generateMessageTag:ra,sendNode:P,groupMetadata:sa,groupToggleEphemeral:ta}=ba,ea=n.userDevicesCache||new node_cache_1.default({stdTTL:Defaults_1.DEFAULT_CACHE_TTLS.USER_DEVICES,useClones:!1});let Q;
const fa=async(a=!1)=>{const b=await Q;if(!b||a||(new Date).getTime()-b.fetchDate.getTime()>1E3*b.ttl)Q=(async()=>{var c=await L({tag:"iq",attrs:{type:"set",xmlns:"w:m",to:WABinary_1.S_WHATSAPP_NET},content:[{tag:"media_conn",attrs:{}}]});c=(0,WABinary_1.getBinaryNodeChild)(c,"media_conn");c={hosts:(0,WABinary_1.getBinaryNodeChildren)(c,"host").map(({attrs:d})=>({hostname:d.hostname,maxContentLengthBytes:+d.maxContentLengthBytes})),auth:c.attrs.auth,ttl:+c.attrs.ttl,fetchDate:new Date};m.debug("fetched media conn");
return c})();return Q},ha=async(a,b,c,d)=>{const e={tag:"receipt",attrs:{id:c[0]}};if("read"===d||"read-self"===d)e.attrs.t=(0,Utils_1.unixTimestampSeconds)().toString();"sender"===d&&(0,WABinary_1.isJidUser)(a)?(e.attrs.recipient=a,e.attrs.to=b):(e.attrs.to=a,b&&(e.attrs.participant=b));d&&(e.attrs.type=(0,WABinary_1.isJidNewsLetter)(a)?"read-self":d);a=c.slice(1);a.length&&(e.content=[{tag:"list",attrs:{},content:a.map(g=>({tag:"item",attrs:{id:g}}))}]);m.debug({attrs:e.attrs,messageIds:c},"sending receipt for messages");
await P(e)},ia=async(a,b)=>{a=(0,Utils_1.aggregateMessageKeysNotFromMe)(a);for(const {jid:c,participant:d,messageIds:e}of a)await ha(c,d,e,b)},R=async(a,b,c)=>{var d;const e=[];b||m.debug("not using cache for devices");const g=[];a=Array.from(new Set(a));for(let f of a){a=null===(d=(0,WABinary_1.jidDecode)(f))||void 0===d?void 0:d.user;f=(0,WABinary_1.jidNormalizedUser)(f);const p=ea.get(a);p&&b?(e.push(...p),m.trace({user:a},"using cache for devices")):g.push({tag:"user",attrs:{jid:f}})}if(!g.length)return e;
b={tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"get",xmlns:"usync"},content:[{tag:"usync",attrs:{sid:ra(),mode:"query",last:"true",index:"0",context:"message"},content:[{tag:"query",attrs:{},content:[{tag:"devices",attrs:{version:"2"}}]},{tag:"list",attrs:{},content:g}]}]};b=await L(b);c=(0,Utils_1.extractDeviceJids)(b,q.creds.me.id,c);b={};for(const f of c)b[f.user]=b[f.user]||[],b[f.user].push(f),e.push(f);for(const f in b)ea.set(f,b[f]);return e},S=async(a,b)=>{var c=!1;let d=[];if(b)d=a;
else{b=a.map(e=>G.jidToSignalProtocolAddress(e));b=await q.keys.get("session",b);for(const e of a)a=G.jidToSignalProtocolAddress(e),b[a]||d.push(e)}d.length&&(m.debug({jidsRequiringFetch:d},"fetching sessions"),c=await L({tag:"iq",attrs:{xmlns:"encrypt",type:"get",to:WABinary_1.S_WHATSAPP_NET},content:[{tag:"key",attrs:{},content:d.map(e=>({tag:"user",attrs:{jid:e}}))}]}),await (0,Utils_1.parseAndInjectE2ESessions)(c,G),c=!0);return c},M=async(a,b,c)=>{b=await O(b,a);const d=(0,Utils_1.encodeWAMessage)(b);
let e=!1;return{nodes:await Promise.all(a.map(async g=>{const {type:f,ciphertext:p}=await G.encryptMessage({jid:g,data:d});"pkmsg"===f&&(e=!0);return{tag:"to",attrs:{jid:g},content:[{tag:"enc",attrs:{v:"2",type:f,...(c||{})},content:p}]}})),shouldIncludeDeviceIdentity:e}},la=async(a,b,{messageId:c,participant:d,additionalAttributes:e,additionalNodes:g,useUserDevicesCache:f,cachedGroupMetadata:p,statusJidList:H})=>{const r=q.creds.me.id;let v=!1;const {user:u,server:I}=(0,WABinary_1.jidDecode)(a),
T="g.us"===I,z="status@broadcast"===a,J="lid"===I,U="newsletter"===I;c=c||(0,Utils_1.generateMessageID)();f=!1!==f;const B=[],A=z?"status@broadcast":(0,WABinary_1.jidEncode)(u,J?"lid":T?"g.us":U?"newsletter":"s.whatsapp.net"),N=[],w=[],ua={deviceSentMessage:{destinationJid:A,message:b}};if(d){T||z||(e={...e,device_fanout:"false"});const {user:t,device:x}=(0,WABinary_1.jidDecode)(d.jid);w.push({user:t,device:x})}await q.keys.transaction(async()=>{var t,x,C,D,h=ja(b);if(T||z){const [K,E]=await Promise.all([(async()=>
{let l=p?await p(a):void 0;l&&m.trace({jid:a,participants:l.participants.length},"using cached group metadata");l||z||(l=await sa(a));return l})(),(async()=>d||z?{}:(await q.keys.get("sender-key-memory",[a]))[a]||{})()]);if(!d){var k=K&&!z?K.participants.map(l=>l.id):[];z&&H&&k.push(...H);k=await R(k,!!f,!1);w.push(...k)}k=await O(b,w.map(l=>(0,WABinary_1.jidEncode)(l.user,J?"lid":"s.whatsapp.net",l.device)));k=(0,Utils_1.encodeWAMessage)(k);const {ciphertext:V,senderKeyDistributionMessage:W}=await G.encryptGroupMessage({group:A,
data:k,meId:r});k=[];for(const {user:l,device:X}of w){var y=(0,WABinary_1.jidEncode)(l,J?"lid":"s.whatsapp.net",X);if(!E[y]||d)k.push(y),E[y]=!0}k.length&&(m.debug({senderKeyJids:k},"sending new sender key"),y={senderKeyDistributionMessage:{axolotlSenderKeyDistributionMessage:W,groupId:A}},await S(k,!1),h=await M(k,y,h?{mediatype:h}:void 0),v=v||h.shouldIncludeDeviceIdentity,B.push(...h.nodes));N.push({tag:"enc",attrs:{v:"2",type:"skmsg"},content:V});await q.keys.set({"sender-key-memory":{[a]:E}})}else if(U){if(null===
(t=b.protocolMessage)||void 0===t?0:t.editedMessage)c=null===(x=b.protocolMessage.key)||void 0===x?void 0:x.id,b=b.protocolMessage.editedMessage;(null===(C=b.protocolMessage)||void 0===C?void 0:C.type)===WAProto_1.proto.Message.ProtocolMessage.Type.REVOKE&&(c=null===(D=b.protocolMessage.key)||void 0===D?void 0:D.id,b={});k=await O(b,[]);k=WAProto_1.proto.Message.encode(k).finish();N.push({tag:"plaintext",attrs:h?{mediatype:h}:{},content:k})}else{const {user:K,device:E}=(0,WABinary_1.jidDecode)(r);
d||(w.push({user:u}),void 0!==E&&0!==E&&w.push({user:K}),t=await R([r,a],!!f,!0),w.push(...t));t=[];x=[];C=[];for(const {user:Y,device:va}of w){D=Y===K;const Z=(0,WABinary_1.jidEncode)(D&&J?(null===(y=null===(k=q.creds)||void 0===k?void 0:k.me)||void 0===y?void 0:y.lid.split(":")[0])||Y:Y,J?"lid":"s.whatsapp.net",va);D?x.push(Z):C.push(Z);t.push(Z)}await S(t,!1);const [{nodes:V,shouldIncludeDeviceIdentity:W},{nodes:l,shouldIncludeDeviceIdentity:X}]=await Promise.all([M(x,ua,h?{mediatype:h}:void 0),
M(C,b,h?{mediatype:h}:void 0)]);B.push(...V);B.push(...l);v=v||W||X}B.length&&N.push({tag:"participants",attrs:{},content:B});h={tag:"message",attrs:{id:c,type:U?F(b):"text",...(e||{})},content:N};d?(0,WABinary_1.isJidGroup)(A)?(h.attrs.to=A,h.attrs.participant=d.jid):(0,WABinary_1.areJidsSameUser)(d.jid,r)?(h.attrs.to=d.jid,h.attrs.recipient=A):h.attrs.to=d.jid:h.attrs.to=A;v&&(h.content.push({tag:"device-identity",attrs:{},content:(0,Utils_1.encodeSignedDeviceIdentity)(q.creds.account,!0)}),m.debug({jid:a},
"adding device identity"));g&&0<g.length?h.content.push(...g):((0,WABinary_1.isJidGroup)(a)||(0,WABinary_1.isJidUser)(a))&&((null===b||void 0===b?0:b.viewOnceMessage)||(null===b||void 0===b?0:b.viewOnceMessageV2)||(null===b||void 0===b?0:b.viewOnceMessageV2Extension)||(null===b||void 0===b?0:b.ephemeralMessage)||(null===b||void 0===b?0:b.templateMessage)||(null===b||void 0===b?0:b.interactiveMessage)||(null===b||void 0===b?0:b.buttonsMessage))&&h.content.push({tag:"biz",attrs:{},content:[{tag:"interactive",
attrs:{type:"native_flow",v:"1"},content:[{tag:"native_flow",attrs:{name:"quick_reply"}}]}]});if(k=wa(b))h.content.push({tag:"biz",attrs:{},content:[{tag:k,attrs:ka(b)}]}),m.debug({jid:a},"adding business node");m.debug({msgId:c},`sending message to ${B.length} devices`);await P(h)});return c},F=a=>a.viewOnceMessage?F(a.viewOnceMessage.message):a.viewOnceMessageV2?F(a.viewOnceMessageV2.message):a.viewOnceMessageV2Extension?F(a.viewOnceMessageV2Extension.message):a.ephemeralMessage?F(a.ephemeralMessage.message):
a.documentWithCaptionMessage?F(a.documentWithCaptionMessage.message):a.reactionMessage?"reaction":a.pollCreationMessage||a.pollCreationMessageV2||a.pollCreationMessageV3||a.pollUpdateMessage?"reaction":ja(a)?"media":"text",ja=a=>{if(a.imageMessage)return"image";if(a.videoMessage)return a.videoMessage.gifPlayback?"gif":"video";if(a.audioMessage)return a.audioMessage.ptt?"ptt":"audio";if(a.contactMessage)return"vcard";if(a.documentMessage)return"document";if(a.contactsArrayMessage)return"contact_array";
if(a.liveLocationMessage)return"livelocation";if(a.stickerMessage)return"sticker";if(a.listMessage)return"list";if(a.listResponseMessage)return"list_response";if(a.buttonsResponseMessage)return"buttons_response";if(a.orderMessage)return"order";if(a.productMessage)return"product";if(a.interactiveResponseMessage)return"native_flow_response"},wa=a=>{if(a.buttonsMessage)return"buttons";if(a.buttonsResponseMessage)return"buttons_response";if(a.interactiveResponseMessage)return"interactive_response";if(a.listMessage)return"list";
if(a.listResponseMessage)return"list_response"},ka=a=>{if(a.templateMessage)return{};if(a.listMessage){a=a.listMessage.listType;if(!a)throw new boom_1.Boom("Expected list type inside message");return{v:"2",type:ListType[a].toLowerCase()}}return{}},aa=(0,Utils_1.getWAUploadToServer)(n,fa),xa=(0,Utils_1.bindWaitForEvent)(ca,"messages.media-update");return{...ba,getPrivacyTokens:async a=>{const b=(0,Utils_1.unixTimestampSeconds)().toString();return await L({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,
type:"set",xmlns:"privacy"},content:[{tag:"tokens",attrs:{},content:a.map(c=>({tag:"token",attrs:{jid:(0,WABinary_1.jidNormalizedUser)(c),t:b,type:"trusted_contact"}}))}]})},assertSessions:S,relayMessage:la,sendReceipt:ha,sendReceipts:ia,getButtonArgs:ka,readMessages:async a=>{const b="all"===(await da()).readreceipts?"read":"read-self";await ia(a,b)},refreshMediaConn:fa,getUSyncDevices:R,createParticipantNodes:M,waUploadToServer:aa,fetchPrivacySettings:da,updateMediaMessage:async a=>{const b=(0,Utils_1.assertMediaContent)(a.message),
c=b.mediaKey,d=(0,Utils_1.encryptMediaRetryRequest)(a.key,c,q.creds.me.id);let e=void 0;await Promise.all([P(d),xa(g=>{if(g=g.find(f=>f.key.id===a.key.id)){if(g.error)e=g.error;else try{const f=(0,Utils_1.decryptMediaRetryData)(g.media,c,g.key.id);if(f.result!==WAProto_1.proto.MediaRetryNotification.ResultType.SUCCESS)throw new boom_1.Boom(`Media re-upload failed by device (${WAProto_1.proto.MediaRetryNotification.ResultType[f.result]})`,{data:f,statusCode:(0,Utils_1.getStatusCodeForMediaRetry)(f.result)||
404});b.directPath=f.directPath;b.url=(0,Utils_1.getUrlFromDirectPath)(b.directPath);m.debug({directPath:f.directPath,key:g.key},"media update successful")}catch(f){e=f}return!0}})]);if(e)throw e;ca.emit("messages.update",[{key:a.key,update:{message:a.message}}]);return a},sendMessage:async(a,b,c={})=>{var d,e,g=q.creds.me.id;if("object"===typeof b&&"disappearingMessagesInChat"in b&&"undefined"!==typeof b.disappearingMessagesInChat&&(0,WABinary_1.isJidGroup)(a))({disappearingMessagesInChat:b}=b),
await ta(a,"boolean"===typeof b?b?Defaults_1.WA_DEFAULT_EPHEMERAL:0:b);else{let f;const p=await (0,Utils_1.generateWAMessage)(a,b,{logger:m,userJid:g,getUrlInfo:u=>(0,link_preview_1.getUrlInfo)(u,{thumbnailWidth:ma,fetchOpts:{timeout:3E3,...(oa||{})},logger:m,uploadImage:na?aa:void 0}),upload:async(u,I)=>{u=await aa(u,{...I,newsletter:(0,WABinary_1.isJidNewsLetter)(a)});f=u.handle;return u},mediaCache:n.mediaCache,options:n.options,...c});g="edit"in b&&!!b.edit;const H="ai"in b&&!!b.ai,r={},v=[];
"delete"in b&&b.delete?(0,WABinary_1.isJidGroup)(null===(d=b.delete)||void 0===d?void 0:d.remoteJid)&&(null===(e=b.delete)||void 0===e||!e.fromMe)||(0,WABinary_1.isJidNewsLetter)(a)?r.edit="8":r.edit="7":g?r.edit=(0,WABinary_1.isJidNewsLetter)(a)?"3":"1":H&&v.push({attrs:{biz_bot:"1"},tag:"bot"});f&&(r.media_id=f);"cachedGroupMetadata"in c&&console.warn("cachedGroupMetadata in sendMessage are deprecated, now cachedGroupMetadata is part of the socket config.");await la(a,p.message,{messageId:p.key.id,
cachedGroupMetadata:c.cachedGroupMetadata,additionalNodes:H?v:c.additionalNodes,additionalAttributes:r,statusJidList:c.statusJidList});n.emitOwnEvents&&process.nextTick(()=>{pa.mutex(()=>qa(p,"append"))});return p}}}};exports.makeMessagesSocket=makeMessagesSocket;
