var __importDefault=this&&this.__importDefault||function(p){return p&&p.__esModule?p:{default:p}};Object.defineProperty(exports,"__esModule",{value:!0});exports.makeMessagesSocket=void 0;
const node_cache_1=__importDefault(require("@cacheable/node-cache")),boom_1=require("@hapi/boom"),WAProto_1=require("../../WAProto"),Defaults_1=require("../Defaults"),Utils_1=require("../Utils"),link_preview_1=require("../Utils/link-preview"),WABinary_1=require("../WABinary"),WAUSync_1=require("../WAUSync"),groups_1=require("./groups"),makeMessagesSocket=p=>{const {logger:m,linkPreviewImageThumbnailWidth:la,generateHighQualityLinkPreview:ma,options:na,patchMessageBeforeSending:aa,cachedGroupMetadata:ba}=
p,D=(0,groups_1.makeGroupsSocket)(p),{ev:ca,authState:q,processingMutex:oa,signalRepository:F,upsertMessage:pa,query:M,fetchPrivacySettings:da,sendNode:N,groupMetadata:qa,groupToggleEphemeral:ra}=D,ea=p.userDevicesCache||new node_cache_1.default({stdTTL:Defaults_1.DEFAULT_CACHE_TTLS.USER_DEVICES,useClones:!1});let O;const fa=async(a=!1)=>{const b=await O;if(!b||a||(new Date).getTime()-b.fetchDate.getTime()>1E3*b.ttl)O=(async()=>{var e=await M({tag:"iq",attrs:{type:"set",xmlns:"w:m",to:WABinary_1.S_WHATSAPP_NET},
content:[{tag:"media_conn",attrs:{}}]});e=(0,WABinary_1.getBinaryNodeChild)(e,"media_conn");e={hosts:(0,WABinary_1.getBinaryNodeChildren)(e,"host").map(({attrs:d})=>({hostname:d.hostname,maxContentLengthBytes:+d.maxContentLengthBytes})),auth:e.attrs.auth,ttl:+e.attrs.ttl,fetchDate:new Date};m.debug("fetched media conn");return e})();return O},ha=async(a,b,e,d)=>{const c={tag:"receipt",attrs:{id:e[0]}};if("read"===d||"read-self"===d)c.attrs.t=(0,Utils_1.unixTimestampSeconds)().toString();"sender"===
d&&(0,WABinary_1.isJidUser)(a)?(c.attrs.recipient=a,c.attrs.to=b):(c.attrs.to=a,b&&(c.attrs.participant=b));d&&(c.attrs.type=d);a=e.slice(1);a.length&&(c.content=[{tag:"list",attrs:{},content:a.map(g=>({tag:"item",attrs:{id:g}}))}]);m.debug({attrs:c.attrs,messageIds:e},"sending receipt for messages");await N(c)},ia=async(a,b)=>{a=(0,Utils_1.aggregateMessageKeysNotFromMe)(a);for(const {jid:e,participant:d,messageIds:c}of a)await ha(e,d,c,b)},P=async(a,b,e)=>{var d;const c=[];b||m.debug("not using cache for devices");
var g=[];a=Array.from(new Set(a));for(let f of a)if(a=null===(d=(0,WABinary_1.jidDecode)(f))||void 0===d?void 0:d.user,f=(0,WABinary_1.jidNormalizedUser)(f),b){const n=ea.get(a);n?(c.push(...n),m.trace({user:a},"using cache for devices")):g.push(f)}else g.push(f);if(!g.length)return c;b=(new WAUSync_1.USyncQuery).withContext("message").withDeviceProtocol();for(const f of g)b.withUser((new WAUSync_1.USyncUser).withId(f));if(g=await D.executeUSyncQuery(b)){e=(0,Utils_1.extractDeviceJids)(null===g||
void 0===g?void 0:g.list,q.creds.me.id,e);g={};for(const f of e)g[f.user]=g[f.user]||[],g[f.user].push(f),c.push(f);for(const f in g)ea.set(f,g[f])}return c},Q=async(a,b)=>{var e=!1;let d=[];if(b)d=a;else{b=a.map(c=>F.jidToSignalProtocolAddress(c));b=await q.keys.get("session",b);for(const c of a)a=F.jidToSignalProtocolAddress(c),b[a]||d.push(c)}d.length&&(m.debug({jidsRequiringFetch:d},"fetching sessions"),e=await M({tag:"iq",attrs:{xmlns:"encrypt",type:"get",to:WABinary_1.S_WHATSAPP_NET},content:[{tag:"key",
attrs:{},content:d.map(c=>({tag:"user",attrs:{jid:c}}))}]}),await (0,Utils_1.parseAndInjectE2ESessions)(e,F),e=!0);return e},J=async(a,b,e)=>{b=await aa(b,a);const d=(0,Utils_1.encodeWAMessage)(b);let c=!1;return{nodes:await Promise.all(a.map(async g=>{const {type:f,ciphertext:n}=await F.encryptMessage({jid:g,data:d});"pkmsg"===f&&(c=!0);return{tag:"to",attrs:{jid:g},content:[{tag:"enc",attrs:{v:"2",type:f,...(e||{})},content:n}]}})),shouldIncludeDeviceIdentity:c}},Y=async(a,b,{messageId:e,participant:d,
additionalAttributes:c,additionalNodes:g,useUserDevicesCache:f,useCachedGroupMetadata:n,statusJidList:K})=>{var r;const x=q.creds.me.id;let y=!1;const {user:R,server:ja}=(0,WABinary_1.jidDecode)(a),S="g.us"===ja,u="status@broadcast"===a,G="lid"===ja;e=e||(0,Utils_1.generateMessageIDV2)(null===(r=D.user)||void 0===r?void 0:r.id);f=!1!==f;n=!1!==n&&!u;const z=[],A=u?"status@broadcast":(0,WABinary_1.jidEncode)(R,G?"lid":S?"g.us":"s.whatsapp.net"),L=[],v=[],sa={deviceSentMessage:{destinationJid:A,message:b}},
H={};if(d){S||u||(c={...c,device_fanout:"false"});const {user:t,device:k}=(0,WABinary_1.jidDecode)(d.jid);v.push({user:t,device:k})}await q.keys.transaction(async()=>{var t,k,B,C=ta(b);C&&(H.mediatype=C);if(null===(t=(0,Utils_1.normalizeMessageContent)(b))||void 0===t?0:t.pinInChatMessage)H["decrypt-fail"]="hide";if(S||u){const [I,E]=await Promise.all([(async()=>{let l=n&&ba?await ba(a):void 0;l&&Array.isArray(null===l||void 0===l?void 0:l.participants)?m.trace({jid:a,participants:l.participants.length},
"using cached group metadata"):u||(l=await qa(a));return l})(),(async()=>d||u?{}:(await q.keys.get("sender-key-memory",[a]))[a]||{})()]);if(!d){var h=I&&!u?I.participants.map(l=>l.id):[];u&&K&&h.push(...K);h=await P(h,!!f,!1);v.push(...h)}h=await aa(b,v.map(l=>(0,WABinary_1.jidEncode)(l.user,G?"lid":"s.whatsapp.net",l.device)));h=(0,Utils_1.encodeWAMessage)(h);const {ciphertext:T,senderKeyDistributionMessage:U}=await F.encryptGroupMessage({group:A,data:h,meId:x});h=[];for(const {user:l,device:V}of v){var w=
(0,WABinary_1.jidEncode)(l,G?"lid":"s.whatsapp.net",V);if(!E[w]||d)h.push(w),E[w]=!0}h.length&&(m.debug({senderKeyJids:h},"sending new sender key"),w={senderKeyDistributionMessage:{axolotlSenderKeyDistributionMessage:U,groupId:A}},await Q(h,!1),h=await J(h,w,H),y=y||h.shouldIncludeDeviceIdentity,z.push(...h.nodes));L.push({tag:"enc",attrs:{v:"2",type:"skmsg"},content:T});await q.keys.set({"sender-key-memory":{[a]:E}})}else{({user:t}=(0,WABinary_1.jidDecode)(x));d||(v.push({user:R}),R!==t&&v.push({user:t}),
"peer"!==(null===c||void 0===c?void 0:c.category)&&(C=await P([x,a],!!f,!0),v.push(...C)));C=[];const I=[],E=[];for(const {user:W,device:ua}of v){const ka=W===t,X=(0,WABinary_1.jidEncode)(ka&&G?(null===(w=null===(h=q.creds)||void 0===h?void 0:h.me)||void 0===w?void 0:w.lid.split(":")[0])||W:W,G?"lid":"s.whatsapp.net",ua);ka?I.push(X):E.push(X);C.push(X)}await Q(C,!1);const [{nodes:T,shouldIncludeDeviceIdentity:U},{nodes:l,shouldIncludeDeviceIdentity:V}]=await Promise.all([J(I,sa,H),J(E,b,H)]);z.push(...T);
z.push(...l);y=y||U||V}z.length&&("peer"===(null===c||void 0===c?void 0:c.category)?(h=null===(B=null===(k=z[0])||void 0===k?void 0:k.content)||void 0===B?void 0:B[0])&&L.push(h):L.push({tag:"participants",attrs:{},content:z}));k=e;B=b.pollCreationMessage||b.pollCreationMessageV2||b.pollCreationMessageV3?"poll":"text";k={tag:"message",attrs:{id:k,type:B,...(c||{})},content:L};d?(0,WABinary_1.isJidGroup)(A)?(k.attrs.to=A,k.attrs.participant=d.jid):(0,WABinary_1.areJidsSameUser)(d.jid,x)?(k.attrs.to=
d.jid,k.attrs.recipient=A):k.attrs.to=d.jid:k.attrs.to=A;y&&(k.content.push({tag:"device-identity",attrs:{},content:(0,Utils_1.encodeSignedDeviceIdentity)(q.creds.account,!0)}),m.debug({jid:a},"adding device identity"));g&&0<g.length?k.content.push(...g):((0,WABinary_1.isJidGroup)(a)||(0,WABinary_1.isJidUser)(a))&&((null===b||void 0===b?0:b.viewOnceMessage)||(null===b||void 0===b?0:b.viewOnceMessageV2)||(null===b||void 0===b?0:b.viewOnceMessageV2Extension)||(null===b||void 0===b?0:b.ephemeralMessage)||
(null===b||void 0===b?0:b.templateMessage)||(null===b||void 0===b?0:b.interactiveMessage)||(null===b||void 0===b?0:b.buttonsMessage))&&k.content.push({tag:"biz",attrs:{},content:[{tag:"interactive",attrs:{type:"native_flow",v:"1"},content:[{tag:"native_flow",attrs:{name:"quick_reply"}}]}]});if(B=va(b))k.content.push({tag:"biz",attrs:{},content:[{tag:B,attrs:wa(b)}]}),m.debug({jid:a},"adding business node");m.debug({msgId:e},`sending message to ${z.length} devices`);await N(k)});return e},ta=a=>{if(a.imageMessage)return"image";
if(a.videoMessage)return a.videoMessage.gifPlayback?"gif":"video";if(a.audioMessage)return a.audioMessage.ptt?"ptt":"audio";if(a.contactMessage)return"vcard";if(a.documentMessage)return"document";if(a.contactsArrayMessage)return"contact_array";if(a.liveLocationMessage)return"livelocation";if(a.stickerMessage)return"sticker";if(a.listMessage)return"list";if(a.listResponseMessage)return"list_response";if(a.buttonsResponseMessage)return"buttons_response";if(a.orderMessage)return"order";if(a.productMessage)return"product";
if(a.interactiveResponseMessage)return"native_flow_response";if(a.groupInviteMessage)return"url"},va=a=>{if(a.buttonsMessage)return"buttons";if(a.buttonsResponseMessage)return"buttons_response";if(a.interactiveResponseMessage)return"interactive_response";if(a.listMessage)return"list";if(a.listResponseMessage)return"list_response"},wa=a=>{if(a.templateMessage)return{};if(a.listMessage){a=a.listMessage.listType;if(!a)throw new boom_1.Boom("Expected list type inside message");return{v:"2",type:ListType[a].toLowerCase()}}return{}},
Z=(0,Utils_1.getWAUploadToServer)(p,fa),xa=(0,Utils_1.bindWaitForEvent)(ca,"messages.media-update");return{...D,getPrivacyTokens:async a=>{const b=(0,Utils_1.unixTimestampSeconds)().toString();return await M({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"privacy"},content:[{tag:"tokens",attrs:{},content:a.map(e=>({tag:"token",attrs:{jid:(0,WABinary_1.jidNormalizedUser)(e),t:b,type:"trusted_contact"}}))}]})},assertSessions:Q,relayMessage:Y,sendReceipt:ha,sendReceipts:ia,readMessages:async a=>
{const b="all"===(await da()).readreceipts?"read":"read-self";await ia(a,b)},refreshMediaConn:fa,waUploadToServer:Z,fetchPrivacySettings:da,sendPeerDataOperationMessage:async a=>{var b;if(null===(b=q.creds.me)||void 0===b||!b.id)throw new boom_1.Boom("Not authenticated");a={protocolMessage:{peerDataOperationRequestMessage:a,type:WAProto_1.proto.Message.ProtocolMessage.Type.PEER_DATA_OPERATION_REQUEST_MESSAGE}};b=(0,WABinary_1.jidNormalizedUser)(q.creds.me.id);return await Y(b,a,{additionalAttributes:{category:"peer",
push_priority:"high_force"}})},createParticipantNodes:J,getUSyncDevices:P,updateMediaMessage:async a=>{const b=(0,Utils_1.assertMediaContent)(a.message),e=b.mediaKey,d=await (0,Utils_1.encryptMediaRetryRequest)(a.key,e,q.creds.me.id);let c=void 0;await Promise.all([N(d),xa(async g=>{if(g=g.find(f=>f.key.id===a.key.id)){if(g.error)c=g.error;else try{const f=await (0,Utils_1.decryptMediaRetryData)(g.media,e,g.key.id);if(f.result!==WAProto_1.proto.MediaRetryNotification.ResultType.SUCCESS)throw new boom_1.Boom(`Media re-upload failed by device (${WAProto_1.proto.MediaRetryNotification.ResultType[f.result]})`,
{data:f,statusCode:(0,Utils_1.getStatusCodeForMediaRetry)(f.result)||404});b.directPath=f.directPath;b.url=(0,Utils_1.getUrlFromDirectPath)(b.directPath);m.debug({directPath:f.directPath,key:g.key},"media update successful")}catch(f){c=f}return!0}})]);if(c)throw c;ca.emit("messages.update",[{key:a.key,update:{message:a.message}}]);return a},sendMessage:async(a,b,e={})=>{var d,c,g,f=q.creds.me.id;if("object"===typeof b&&"disappearingMessagesInChat"in b&&"undefined"!==typeof b.disappearingMessagesInChat&&
(0,WABinary_1.isJidGroup)(a))({disappearingMessagesInChat:b}=b),await ra(a,"boolean"===typeof b?b?Defaults_1.WA_DEFAULT_EPHEMERAL:0:b);else{const n=await (0,Utils_1.generateWAMessage)(a,b,{logger:m,userJid:f,getUrlInfo:y=>(0,link_preview_1.getUrlInfo)(y,{thumbnailWidth:la,fetchOpts:{timeout:3E3,...(na||{})},logger:m,uploadImage:ma?Z:void 0}),getProfilePicUrl:D.profilePictureUrl,upload:Z,mediaCache:p.mediaCache,options:p.options,messageId:(0,Utils_1.generateMessageIDV2)(null===(d=D.user)||void 0===
d?void 0:d.id),...e});d="edit"in b&&!!b.edit;f="pin"in b&&!!b.pin;const K="poll"in b&&!!b.poll,r={},x=[];"delete"in b&&b.delete?!(0,WABinary_1.isJidGroup)(null===(c=b.delete)||void 0===c?void 0:c.remoteJid)||(null===(g=b.delete)||void 0===g?0:g.fromMe)?r.edit="7":r.edit="8":d?r.edit="1":f?r.edit="2":K&&x.push({tag:"meta",attrs:{polltype:"creation"}});"cachedGroupMetadata"in e&&console.warn("cachedGroupMetadata in sendMessage are deprecated, now cachedGroupMetadata is part of the socket config.");
await Y(a,n.message,{messageId:n.key.id,useCachedGroupMetadata:e.useCachedGroupMetadata,additionalAttributes:r,statusJidList:e.statusJidList,additionalNodes:x});p.emitOwnEvents&&process.nextTick(()=>{oa.mutex(()=>pa(n,"append"))});return n}}}};exports.makeMessagesSocket=makeMessagesSocket;
