Object.defineProperty(exports,"__esModule",{value:!0});exports.extractNewsletterMetadata=exports.makeNewsletterSocket=void 0;
const Types_1=require("../Types"),Utils_1=require("../Utils"),WABinary_1=require("../WABinary"),groups_1=require("./groups"),makeNewsletterSocket=m=>{const d=(0,groups_1.makeGroupsSocket)(m),{authState:n,signalRepository:p,query:g,generateMessageTag:h}=d,q=new TextEncoder,k=async(a,b,c)=>g({tag:"iq",attrs:{id:h(),type:b,xmlns:"newsletter",to:a},content:c}),e=async(a,b,c)=>g({tag:"iq",attrs:{id:h(),type:"get",xmlns:"w:mex",to:WABinary_1.S_WHATSAPP_NET},content:[{tag:"query",attrs:{query_id:b},content:q.encode(JSON.stringify({variables:{newsletter_id:a,
...c}}))}]}),v=async(a,b)=>{let c;"messages"===b?c=(0,WABinary_1.getBinaryNodeChild)(a,"messages"):(a=(0,WABinary_1.getBinaryNodeChild)(a,"message_updates"),c=(0,WABinary_1.getBinaryNodeChild)(a,"messages"));return await Promise.all((0,WABinary_1.getAllBinaryNodeChildren)(c).map(async f=>{var l,u;f.attrs.from=null===c||void 0===c?void 0:c.attrs.jid;var r=parseInt((null===(u=null===(l=(0,WABinary_1.getBinaryNodeChild)(f,"views_count"))||void 0===l?void 0:l.attrs)||void 0===u?void 0:u.count)||"0");
l=(0,WABinary_1.getBinaryNodeChild)(f,"reactions");l=(0,WABinary_1.getBinaryNodeChildren)(l,"reaction").map(({attrs:t})=>({count:+t.count,code:t.code}));r={server_id:f.attrs.server_id,views:r,reactions:l};if("messages"===b){const {fullMessage:t,decrypt:w}=await (0,Utils_1.decryptMessageNode)(f,n.creds.me.id,n.creds.me.lid||"",p,m.logger);await w();r.message=t}return r}))};return{...d,subscribeNewsletterUpdates:async a=>{var b;a=await k(a,"set",[{tag:"live_updates",attrs:{},content:[]}]);return null===
(b=(0,WABinary_1.getBinaryNodeChild)(a,"live_updates"))||void 0===b?void 0:b.attrs},newsletterReactionMode:async(a,b)=>{await e(a,Types_1.QueryIds.JOB_MUTATION,{updates:{settings:{reaction_codes:{value:b}}}})},newsletterUpdateDescription:async(a,b)=>{await e(a,Types_1.QueryIds.JOB_MUTATION,{updates:{description:b||"",settings:null}})},newsletterUpdateName:async(a,b)=>{await e(a,Types_1.QueryIds.JOB_MUTATION,{updates:{name:b,settings:null}})},newsletterUpdatePicture:async(a,b)=>{({img:b}=await (0,Utils_1.generateProfilePicture)(b));
await e(a,Types_1.QueryIds.JOB_MUTATION,{updates:{picture:b.toString("base64"),settings:null}})},newsletterRemovePicture:async a=>{await e(a,Types_1.QueryIds.JOB_MUTATION,{updates:{picture:"",settings:null}})},newsletterUnfollow:async a=>{await e(a,Types_1.QueryIds.UNFOLLOW)},newsletterFollow:async a=>{await e(a,Types_1.QueryIds.FOLLOW)},newsletterUnmute:async a=>{await e(a,Types_1.QueryIds.UNMUTE)},newsletterMute:async a=>{await e(a,Types_1.QueryIds.MUTE)},newsletterAction:async(a,b)=>{await e(a,
b.toUpperCase())},newsletterCreate:async(a,b,c)=>{await g({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,xmlns:"tos",id:h(),type:"set"},content:[{tag:"notice",attrs:{id:"20601218",stage:"5"},content:[]}]});a=await e(void 0,Types_1.QueryIds.CREATE,{input:{name:a,description:b,settings:{reaction_codes:{value:c.toUpperCase()}}}});return(0,exports.extractNewsletterMetadata)(a,!0)},newsletterMetadata:async(a,b,c)=>{a=await e(void 0,Types_1.QueryIds.METADATA,{input:{key:b,type:a.toUpperCase(),view_role:c||
"GUEST"},fetch_viewer_metadata:!0,fetch_full_image:!0,fetch_creation_time:!0});return(0,exports.extractNewsletterMetadata)(a)},newsletterAdminCount:async a=>{var b,c;a=await e(a,Types_1.QueryIds.ADMIN_COUNT);a=null===(c=null===(b=(0,WABinary_1.getBinaryNodeChild)(a,"result"))||void 0===b?void 0:b.content)||void 0===c?void 0:c.toString();return JSON.parse(a).data[Types_1.XWAPaths.ADMIN_COUNT].admin_count},newsletterChangeOwner:async(a,b)=>{await e(a,Types_1.QueryIds.CHANGE_OWNER,{user_id:b})},newsletterDemote:async(a,
b)=>{await e(a,Types_1.QueryIds.DEMOTE,{user_id:b})},newsletterDelete:async a=>{await e(a,Types_1.QueryIds.DELETE)},newsletterReactMessage:async(a,b,c)=>{await g({tag:"message",attrs:{to:a,...(c?{}:{edit:"7"}),type:"reaction",server_id:b,id:(0,Utils_1.generateMessageID)()},content:[{tag:"reaction",attrs:c?{code:c}:{}}]})},newsletterFetchMessages:async(a,b,c,f)=>{a=await k(WABinary_1.S_WHATSAPP_NET,"get",[{tag:"messages",attrs:{type:a,...("invite"===a?{key:b}:{jid:b}),count:c.toString(),after:(null===
f||void 0===f?void 0:f.toString())||"100"}}]);return await v(a,"messages")},newsletterFetchUpdates:async(a,b,c,f)=>{a=await k(a,"get",[{tag:"message_updates",attrs:{count:b.toString(),after:(null===c||void 0===c?void 0:c.toString())||"100",since:(null===f||void 0===f?void 0:f.toString())||"0"}}]);return await v(a,"updates")}}};exports.makeNewsletterSocket=makeNewsletterSocket;
const extractNewsletterMetadata=(m,d)=>{var n,p,g,h,q,k,e;m=null===(p=null===(n=(0,WABinary_1.getBinaryNodeChild)(m,"result"))||void 0===n?void 0:n.content)||void 0===p?void 0:p.toString();d=JSON.parse(m).data[d?Types_1.XWAPaths.CREATE:Types_1.XWAPaths.NEWSLETTER];return{id:d.id,state:d.state.type,creation_time:+d.thread_metadata.creation_time,name:d.thread_metadata.name.text,nameTime:+d.thread_metadata.name.update_time,description:d.thread_metadata.description.text,descriptionTime:+d.thread_metadata.description.update_time,
invite:d.thread_metadata.invite,handle:d.thread_metadata.handle,picture:(null===(g=d.thread_metadata.picture)||void 0===g?void 0:g.direct_path)||null,preview:(null===(h=d.thread_metadata.preview)||void 0===h?void 0:h.direct_path)||null,reaction_codes:null===(e=null===(k=null===(q=d.thread_metadata)||void 0===q?void 0:q.settings)||void 0===k?void 0:k.reaction_codes)||void 0===e?void 0:e.value,subscribers:+d.thread_metadata.subscribers_count,verification:d.thread_metadata.verification,viewer_metadata:d.viewer_metadata}};
exports.extractNewsletterMetadata=extractNewsletterMetadata;
