Object.defineProperty(exports,"__esModule",{value:!0});exports.decryptPollVote=exports.getChatId=exports.shouldIncrementChatUnread=exports.isRealMessage=exports.cleanMessage=void 0;
const WAProto_1=require("../../WAProto"),Types_1=require("../Types"),messages_1=require("../Utils/messages"),WABinary_1=require("../WABinary"),crypto_1=require("./crypto"),generics_1=require("./generics"),history_1=require("./history"),REAL_MSG_STUB_TYPES=new Set([Types_1.WAMessageStubType.CALL_MISSED_GROUP_VIDEO,Types_1.WAMessageStubType.CALL_MISSED_GROUP_VOICE,Types_1.WAMessageStubType.CALL_MISSED_VIDEO,Types_1.WAMessageStubType.CALL_MISSED_VOICE]),REAL_MSG_REQ_ME_STUB_TYPES=new Set([Types_1.WAMessageStubType.GROUP_PARTICIPANT_ADD]),
cleanMessage=(a,p)=>{function f(e){a.key.fromMe||(e.fromMe=e.fromMe?!1:(0,WABinary_1.areJidsSameUser)(e.participant||e.remoteJid,p),e.remoteJid=a.key.remoteJid,e.participant=e.participant||a.key.participant)}a.key.remoteJid=(0,WABinary_1.jidNormalizedUser)(a.key.remoteJid);a.key.participant=a.key.participant?(0,WABinary_1.jidNormalizedUser)(a.key.participant):void 0;const b=(0,messages_1.normalizeMessageContent)(a.message);(null===b||void 0===b?0:b.reactionMessage)&&f(b.reactionMessage.key);(null===
b||void 0===b?0:b.pollUpdateMessage)&&f(b.pollUpdateMessage.pollCreationMessageKey)};exports.cleanMessage=cleanMessage;
const isRealMessage=(a,p)=>{var f;const b=(0,messages_1.normalizeMessageContent)(a.message),e=!!(0,messages_1.getContentType)(b);return(!!b||REAL_MSG_STUB_TYPES.has(a.messageStubType)||REAL_MSG_REQ_ME_STUB_TYPES.has(a.messageStubType)&&(null===(f=a.messageStubParameters)||void 0===f?void 0:f.some(u=>(0,WABinary_1.areJidsSameUser)(p,u))))&&e&&!(null===b||void 0===b?0:b.protocolMessage)&&!(null===b||void 0===b?0:b.reactionMessage)&&!(null===b||void 0===b?0:b.pollUpdateMessage)};
exports.isRealMessage=isRealMessage;const shouldIncrementChatUnread=a=>!a.key.fromMe&&!a.messageStubType;exports.shouldIncrementChatUnread=shouldIncrementChatUnread;const getChatId=({remoteJid:a,participant:p,fromMe:f})=>!(0,WABinary_1.isJidBroadcast)(a)||(0,WABinary_1.isJidStatusBroadcast)(a)||f?a:p;exports.getChatId=getChatId;
function decryptPollVote({encPayload:a,encIv:p},{pollCreatorJid:f,pollMsgId:b,pollEncKey:e,voterJid:u}){f=Buffer.concat([Buffer.from(b),Buffer.from(f),Buffer.from(u),Buffer.from("Poll Vote"),new Uint8Array([1])]);e=(0,crypto_1.hmacSign)(e,new Uint8Array(32),"sha256");e=(0,crypto_1.hmacSign)(f,e,"sha256");b=Buffer.from(`${b}\u0000${u}`);a=(0,crypto_1.aesDecryptGCM)(a,e,p,b);return WAProto_1.proto.Message.PollVoteMessage.decode(a)}exports.decryptPollVote=decryptPollVote;
const processMessage=async(a,{shouldProcessHistoryMsg:p,placeholderResendCache:f,ev:b,creds:e,keyStore:u,logger:g,options:N,getMessage:O})=>{var h,y,z,A,B,C,v,r,D,E,F,G,H,I,x;const J=e.me.id,{accountSettings:K}=e,l={id:(0,WABinary_1.jidNormalizedUser)((0,exports.getChatId)(a.key))},M=(0,exports.isRealMessage)(a,J);M&&(l.messages=[{message:a}],l.conversationTimestamp=(0,generics_1.toNumber)(a.messageTimestamp),(0,exports.shouldIncrementChatUnread)(a)&&(l.unreadCount=(l.unreadCount||0)+1));var d=(0,messages_1.normalizeMessageContent)(a.message);
(M||(null===(y=null===(h=null===d||void 0===d?void 0:d.reactionMessage)||void 0===h?void 0:h.key)||void 0===y?0:y.fromMe))&&(null===K||void 0===K?0:K.unarchiveChats)&&(l.archived=!1,l.readOnly=!1);if(h=null===d||void 0===d?void 0:d.protocolMessage)switch(h.type){case WAProto_1.proto.Message.ProtocolMessage.Type.HISTORY_SYNC_NOTIFICATION:var c=h.historySyncNotification;var k=!(null===(z=e.processedHistoryMessages)||void 0===z?0:z.length);null===g||void 0===g||g.info({histNotification:c,process:p,id:a.key.id,
isLatest:k},"got history notification");p&&(c.syncType!==WAProto_1.proto.HistorySync.HistorySyncType.ON_DEMAND&&b.emit("creds.update",{processedHistoryMessages:[...(e.processedHistoryMessages||[]),{key:a.key,messageTimestamp:a.messageTimestamp}]}),d=await (0,history_1.downloadAndProcessHistorySyncNotification)(c,N),b.emit("messaging-history.set",{...d,isLatest:c.syncType!==WAProto_1.proto.HistorySync.HistorySyncType.ON_DEMAND?k:void 0,peerDataRequestSessionId:c.peerDataRequestSessionId}));break;case WAProto_1.proto.Message.ProtocolMessage.Type.APP_STATE_SYNC_KEY_SHARE:const q=
h.appStateSyncKeyShare.keys;if(null===q||void 0===q?0:q.length){let n="";await u.transaction(async()=>{const t=[];for(const {keyData:P,keyId:Q}of q){const L=Buffer.from(Q.keyId).toString("base64");t.push(L);await u.set({"app-state-sync-key":{[L]:P}});n=L}null===g||void 0===g||g.info({newAppStateSyncKeyId:n,newKeys:t},"injecting new app state sync keys")});b.emit("creds.update",{myAppStateKeyId:n})}else null===g||void 0===g||g.info({protocolMsg:h},"recv app state sync with 0 keys");break;case WAProto_1.proto.Message.ProtocolMessage.Type.REVOKE:b.emit("messages.update",
[{key:{...a.key,id:h.key.id},update:{message:null,messageStubType:Types_1.WAMessageStubType.REVOKE,key:a.key}}]);break;case WAProto_1.proto.Message.ProtocolMessage.Type.EPHEMERAL_SETTING:Object.assign(l,{ephemeralSettingTimestamp:(0,generics_1.toNumber)(a.messageTimestamp),ephemeralExpiration:h.ephemeralExpiration||null});break;case WAProto_1.proto.Message.ProtocolMessage.Type.PEER_DATA_OPERATION_REQUEST_RESPONSE_MESSAGE:const m=h.peerDataOperationRequestResponseMessage;if(m){null===f||void 0===f||
f.del(m.stanzaId);({peerDataOperationResult:c}=m);for(const n of c)if({placeholderMessageResendResponse:c}=n,c){const t=WAProto_1.proto.WebMessageInfo.decode(c.webMessageInfoBytes);setTimeout(()=>{b.emit("messages.upsert",{messages:[t],type:"notify",requestId:m.stanzaId})},500)}}case WAProto_1.proto.Message.ProtocolMessage.Type.MESSAGE_EDIT:b.emit("messages.update",[{key:{...a.key,id:null===(A=h.key)||void 0===A?void 0:A.id},update:{message:{editedMessage:{message:h.editedMessage}},messageTimestamp:h.timestampMs?
Math.floor((0,generics_1.toNumber)(h.timestampMs)/1E3):a.messageTimestamp}}])}else if(null===d||void 0===d?0:d.reactionMessage)b.emit("messages.reaction",[{reaction:{...d.reactionMessage,key:a.key},key:null===(B=d.reactionMessage)||void 0===B?void 0:B.key}]);else if(a.messageStubType){const q=null===(C=a.key)||void 0===C?void 0:C.remoteJid;let m;d=n=>b.emit("group-participants.update",{id:q,author:a.participant,participants:m,action:n});k=n=>{var t;b.emit("groups.update",[{id:q,...n,author:null!==
(t=a.participant)&&void 0!==t?t:void 0}])};var w=()=>m.find(n=>(0,WABinary_1.areJidsSameUser)(J,n));switch(a.messageStubType){case Types_1.WAMessageStubType.GROUP_PARTICIPANT_CHANGE_NUMBER:m=a.messageStubParameters||[];d("modify");break;case Types_1.WAMessageStubType.GROUP_PARTICIPANT_LEAVE:case Types_1.WAMessageStubType.GROUP_PARTICIPANT_REMOVE:m=a.messageStubParameters||[];d("remove");w()&&(l.readOnly=!0);break;case Types_1.WAMessageStubType.GROUP_PARTICIPANT_ADD:case Types_1.WAMessageStubType.GROUP_PARTICIPANT_INVITE:case Types_1.WAMessageStubType.GROUP_PARTICIPANT_ADD_REQUEST_JOIN:m=
a.messageStubParameters||[];w()&&(l.readOnly=!1);d("add");break;case Types_1.WAMessageStubType.GROUP_PARTICIPANT_DEMOTE:m=a.messageStubParameters||[];d("demote");break;case Types_1.WAMessageStubType.GROUP_PARTICIPANT_PROMOTE:m=a.messageStubParameters||[];d("promote");break;case Types_1.WAMessageStubType.GROUP_CHANGE_ANNOUNCE:c=null===(v=a.messageStubParameters)||void 0===v?void 0:v[0];k({announce:"true"===c||"on"===c});break;case Types_1.WAMessageStubType.GROUP_CHANGE_RESTRICT:c=null===(r=a.messageStubParameters)||
void 0===r?void 0:r[0];k({restrict:"true"===c||"on"===c});break;case Types_1.WAMessageStubType.GROUP_CHANGE_SUBJECT:c=null===(D=a.messageStubParameters)||void 0===D?void 0:D[0];l.name=c;k({subject:c});break;case Types_1.WAMessageStubType.GROUP_CHANGE_DESCRIPTION:c=null===(E=a.messageStubParameters)||void 0===E?void 0:E[0];l.description=c;k({desc:c});break;case Types_1.WAMessageStubType.GROUP_CHANGE_INVITE_LINK:c=null===(F=a.messageStubParameters)||void 0===F?void 0:F[0];k({inviteCode:c});break;case Types_1.WAMessageStubType.GROUP_MEMBER_ADD_MODE:c=
null===(G=a.messageStubParameters)||void 0===G?void 0:G[0];k({memberAddMode:"all_member_add"===c});break;case Types_1.WAMessageStubType.GROUP_MEMBERSHIP_JOIN_APPROVAL_MODE:c=null===(H=a.messageStubParameters)||void 0===H?void 0:H[0];k({joinApprovalMode:"on"===c});break;case Types_1.WAMessageStubType.GROUP_MEMBERSHIP_JOIN_APPROVAL_REQUEST_NON_ADMIN_ADD:k=null===(I=a.messageStubParameters)||void 0===I?void 0:I[0],d=null===(x=a.messageStubParameters)||void 0===x?void 0:x[1],w=null===(c=a.messageStubParameters)||
void 0===c?void 0:c[2],b.emit("group.join-request",{id:q,author:a.participant,participant:k,action:d,method:w})}}else if(null===d||void 0===d?0:d.pollUpdateMessage)if(c=d.pollUpdateMessage.pollCreationMessageKey,v=await O(c)){r=(0,WABinary_1.jidNormalizedUser)(J);x=(0,generics_1.getKeyAuthor)(c,r);r=(0,generics_1.getKeyAuthor)(a.key,r);v=null===(k=v.messageContextInfo)||void 0===k?void 0:k.messageSecret;try{w=decryptPollVote(d.pollUpdateMessage.vote,{pollEncKey:v,pollCreatorJid:x,pollMsgId:c.id,voterJid:r}),
b.emit("messages.update",[{key:c,update:{pollUpdates:[{pollUpdateMessageKey:a.key,vote:w,senderTimestampMs:d.pollUpdateMessage.senderTimestampMs.toNumber()}]}}])}catch(q){null===g||void 0===g||g.warn({err:q,creationMsgKey:c},"failed to decrypt poll vote")}}else null===g||void 0===g||g.warn({creationMsgKey:c},"poll creation message not found, cannot decrypt update");1<Object.keys(l).length&&b.emit("chats.update",[l])};exports.default=processMessage;
